### ISSUE TITLE
Not working on macOS (🎬 video included)

### ISSUE THREAD

**Issue by omenking** [lambdalisue/fern.vim#317]
I cannot get fern.vim to work on macOS. 
I get no errors. A minimal install does nothing:

```
if exists('+compatible') && &compatible
  set nocompatible
endif

set packpath=
set runtimepath^=/Users/andrewbrown/.vim/plugged/fern.vim

filetype plugin indent on
syntax on
```
I write in more detail my attempts in this comment from a closed ticket
https://github.com/lambdalisue/fern.vim/issues/293#issuecomment-808752482

Here I show my attempts to debug the issue:

https://youtu.be/q6C_llQpLCE

**Comment by omenking** [comment]
I did a sanity check and installed it on Windows Subsystem Linux (WSL) on my other computer and it worked as expected.
So there is something wrong with macOS

**Comment by lambdalisue** [comment]
Thanks for providing a minimal vimrc :+1: However, I could not reproduce.
What is the version of Vim or Neovim and your macOS.

![CleanShot 2021-03-28 at 14 36 31](https://user-images.githubusercontent.com/546312/112743519-0209cc00-8fd3-11eb-880e-4606ffad5d17.png)

Fern would be disabled if you are using older Vim/Neovim than above.

**Comment by lambdalisue** [comment]
> I write in more detail my attempts in this comment from a closed ticket
> #293 (comment)

I didn't notice that. Please rewrite all of that to **this** PR instead.

**Comment by lambdalisue** [comment]
The minimum supported version of Vim is 8.1.2269 rather than 8.1.0994 thus please upgrade your Vim first. The version you've found is not minimum supported version but internal minimum working version.

Additionally, how did you get your Vim? I'm using macOS Catalina (10.15.7) and the builtin Vim version is 8.1.2292 or the homebrew version is 8.2.2600 thus both versions are way newer than what you see.

**Comment by omenking** [comment]
I will attempt an upgrade of VIM and report my findings.
