### ISSUE TITLE
Option -width does not work

### ISSUE THREAD

**Issue by krehwell** [lambdalisue/fern.vim#350]
I made mapping 
```vim
nnoremap <silent> <Leader>pv :Fern . -drawer -reveal=% -width=27 -toggle<CR>
```
The width was working before, but now it does not work anymore, the width of the resized drawer will just remain the same after toggle

**Comment by lambdalisue** [comment]
Use `zoom:reset` action. https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L790

**Comment by krehwell** [comment]
any way to make a mapping for keymap then call fern action?
``` vim
nnoremap <silent> <Leader>pv :Fern . -drawer -reveal=% -width=27 -toggle<CR> <Plug>(fern-action-zoom:reset)
```
this one does not work (I know it is dumb mapping, but ad least I tried)

**Comment by lambdalisue** [comment]
It does not work because you are using `nnoremap`. 
However, replacing `nnoremap` to `nmap` does not work while `:Fern . -drawer -reveal=% ...<CR>` part should not be remapped.

So first create `<Plug>(my-fern-toggle)` or whatever for complicated command and use it with action like

```vim
nnoremap <silent> <Plug>(my-fern-toggle) :Fern . -drawer -reveal=% -width=27 -toggle<CR>
nmap <Leader>pv <Plug>(my-fern-toggle)<Plug>(fern-action-zoom:reset)
```

You may need to put `<Plug>(fern-wait)` between `<Plug>(my-fern-toggle)` and `<Plug>(fern-action-zoom:reset)`.

**Comment by krehwell** [comment]
waw, thank you so much. great work dev
