### ISSUE TITLE
Add 'expand-all' or whatever action to expand all children recursively

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/fern.vim#39]
Sometimes user want to see all childrens in one action.

**Comment by lambdalisue** [comment]
I can't be bothered to do this while it's quite difficult and nobody wants this feature.

**Comment by egeesin** [comment]
I just want to let you know that I'm actually looking for this exact feature (or any workaround if possible) because in a complex directory i'm working on, I want to see the working directory tree in the drawer without executing a command or any hassle. Maybe there should be an option to specify the depth?

I'm also guessing that might be a trade-off for latency but if there's any way to including this feature without compromising the main concepts/principles of this plugin, I'd be very glad!

**Comment by lambdalisue** [comment]
Thanks for the comment. Well, unfortunately, this is not because of performance but difficulties to implement while fern works in an asynchronous manner. We need to handle Promise callback hell in Vim script to implement this which is too difficult for humans 😅
