### ISSUE TITLE
No window picker labels are shown when `set lstatstatus=3` is used on Neovim

### ISSUE THREAD

**Issue by bstaint** [lambdalisue/fern.vim#420]
neovim nightly version.
When `laststatus` set 3 `Window selector` will not work well

**Comment by lambdalisue** [comment]
Please explain what is `laststatus=3` while that's Neovim specific feature and users, including me, may not know the detail.

**Comment by bstaint** [comment]
> 	The value of this option influences when the last window will have a
	status line:
		0: never
		1: only if there are at least two windows
		2: always
		3: always and ONLY the last window

https://github.com/neovim/neovim/issues/9342

**Comment by ovidius72** [comment]
If laststatus=3 is used we are non longer able to see the window picker where you want to open the buffer.
I don't know if it's possibile to show the window label in a floating window or something like that. 
This is because with that option only a global status line is visible.

**Comment by bluz71** [comment]
Neovim 0.8 will provide a `winbar` option, which will be like a statusline but at the top of each window.

When `laststatus=3` is set it makes sense to also set winbar. Hence it follows that fern should use winbar for window selection.

At some point I will experiment with winbar, I believe it will be the correct solution for this issue. Also, I think it should be a simple implementation since winbar uses the same syntax as statusline.

**Comment by lambdalisue** [comment]
Does `laststatus=3` is provided from Neovim 0.8? If so, `winbar` sounds good alternative for Neovim 0.8

**Comment by bluz71** [comment]
`laststatus=3` was added to Neovim 0.7
`winbar` will be added to upcoming Neovim 0.8, but is available in Neovim nightfly builds.

It makes sense to use both together, but not mandatory.

For this issue I suggest that window selector target `winbar` if it exists and is set.

**Comment by bluz71** [comment]
Hello @lambdalisue,

I have just been testing Neovim's global statusline, `laststatus=3`, in combination with `winbar` and I believe it will be a solution for this issue.

Screenshots, firstly a layout with global statusline and winbar enabled (notice the filenames at the top-left of each window):

<img width="1440" alt="winbar" src="https://user-images.githubusercontent.com/11382509/172771690-1008cad6-dd52-42eb-8f73-225b1ca9293b.png">

Now with my quick hack of fern's `WindowSelector.vim` file:

<img width="1440" alt="winbar_selector" src="https://user-images.githubusercontent.com/11382509/172771865-73649f8a-d018-47c9-bf4c-8c2196437c42.png">

Works perfect in-my-opinion.
I genuinely believe 90% of Neovim folks who enable global statusline will also enable `winbar`.

Hence I think fern.vim can easily be made to work in this scenario.

I think the algorithm should be something like this:

```
if laststatus == 3 && (!exists('&winbar') || winbar == empty)
  no window selector, do nothing, maybe print a message that window selector is disabled
elseif exists('&winbar') && winbar == something
  window selector uses winbar
else
  window selector uses traditional statusbar
```

The file of interest is [WindowSelector.vim](https://github.com/lambdalisue/fern.vim/blob/master/autoload/vital/_fern/App/WindowSelector.vim#L10).

Points of interest:

- [Line 24](https://github.com/lambdalisue/fern.vim/blob/master/autoload/vital/_fern/App/WindowSelector.vim#L24)
- [Line 36](https://github.com/lambdalisue/fern.vim/blob/master/autoload/vital/_fern/App/WindowSelector.vim#L36)
- [Line 51](https://github.com/lambdalisue/fern.vim/blob/master/autoload/vital/_fern/App/WindowSelector.vim#L51)

`&statusline` can be replaced with `&winbar` if winbar is active. `winbar` uses the exact same syntax as `statusline`.

It would be nice to fix this soon, especially because I am now using winbar myself.

**Comment by lambdalisue** [comment]
Thanks but I've been a bit busy so I'll check it on this weekend. I'm sorry for that.

btw, a PR on https://github.com/lambdalisue/vital-Whisky would accerelate to solve this issue 👍

**Comment by bluz71** [comment]
That's ok.

I will try and produce a PR for the vital-Whiskey repo in the next day or so.

Cheers.

**Comment by lambdalisue** [comment]
@ovidius72 @bstaint @bluz71 Could you please confirm that if #430 solve this issue?

**Comment by bstaint** [comment]
It's great, Tks.

**Comment by bluz71** [comment]
Thanks @lambdalisue, the just merged PR works great.
